name: wazo-google
namespace: official
version: 0.0.1
author: Wazo Team
display_name: Google Authentication
plugin_format_version: 1
min_wazo_version: 17.17
tags:
  - beta
  - application
homepage: http://www.wazo.io
