debian_depends:
  - python3-flask
  - python3-marshmallow
  - python3-requests
  - python3-requests-oauthlib
  - wazo-auth
  - xivo-auth-client-python3
  - xivo-lib-python-python3
description: Add google as an external authentication
display_name: Google integration
homepage: https://github.com/tinxhq/wazo-google
author: Wazo Team
name: wazo-google
namespace: official
plugin_format_version: 1
version: 1.0.0-1
tags:
  - authentication
