version: '3.7'
services:
  sync:
    depends_on:
      - auth-mock
      - google.com
      - postgres-auth
      - postgres-dird
      - rabbitmq
    environment:
      TARGETS: "auth-mock:9497 google.com:443 postgres-auth:5432 postgres-dird:5432 rabbitmq:5672"
